name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add setup-ruby action to set the Ruby version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'  # or another compatible version
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
          jekyll_env: "RUBY_VERSION=3.3.4"
          ruby-version: "3.3.4"
